### ISSUE TITLE
Allow updating (PUT) of annotations

### ISSUE THREAD

**Issue by azaroth42** [sul-dlss/triannon#13]
In the same way that annotations are POSTed, annotations or component resources may be PUT to Triannon at a specific URI.  Triannon _must_ then update the corresponding resources in Fedora4, using the same workflow as to create the annotation in the first place.
- [ ] turtle
- [ ] json-ld with OA context (see #120, #121)
- [ ] json-ld with IIIF context (see #120, #121)
- [ ] integration tests
- [ ] honor Content-Type Http Header (and jsonld context there if present) (see #36)
- [ ] honor Accept Http Header for the response (see #20)
