### ISSUE TITLE
use rdf-vocab in place of 4 local rdf-xxx gems

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/triannon#164]
if vocabs aren't in ruby-rdf/rdf-vocab, submit pull requests;  then use this gem and remove old ones.

- [x] add "remove_xxx_triples" methods to triannon gem

- [x] rdf-open_annotation (sul-dlss/rdf-open_annotation#3)
- [x] rdf-ldp (sul-dlss/rdf-ldp#3)
- [x] rdf-fcrepo4 (sul-dlss/rdf-fcrepo4#3)
- [x] rdf-iiif (sul-dlss/rdf-iiif#1)

**Comment by ndushay** [comment]
- [ ] IIIF vocab in rdf-vocab  ruby-rdf/rdf-vocab#14
- [ ] new rdf-vocab gem released
- [ ] triannon gem doesn't use rdf-iiif

then we're done!
